# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Designation',
        ),
        migrations.AddField(
            model_name='post',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
