# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170310_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currentsalary',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expectedsalary',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
