# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170310_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='coverletter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
