# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170310_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
